### ISSUE TITLE
Incorrect code generation on return statements with parenthesised expressions

### ISSUE THREAD

**Issue by RoystonS** [6to5/6to5#349]
6to5 does something quite strange with the following code, causing incorrect code to be generated:

```javascript
function test() {
	return (
		// comment
		true
	);
}
console.log(test());
```

It is transpiled (with 6to5 v2.1.0) to:

```javascript
"use strict";

function test() {
  return;
  // comment
  true;
}
console.log(test());
```

The first program correctly emits 'true', the second 'undefined', due to the bad placement of the return statement.

(Interestingly, with 6to5 v2.0.2, the semicolon after the return statement is not present, but is automatically inserted by JS anyway due to JS ASI rules.)

No, this isn't terribly _realistic_ code: it's just a test case I've boiled down from a real problem use case taken from the Facebook React sourcecode (in https://github.com/facebook/react/blob/v0.12.2/src/vendor/core/createArrayFrom.js#L30-L52)

**Comment by sebmck** [comment]
Sorry for the delay! Fixed as of 2.3.2. It now outputs correct/working code although the whitespace is weird so I'll have to revisit it when I get more time, thanks!

**Comment by jnu** [comment]
Still seeing this issue if I use multiple parentheticals in the return:

Input:
```javascript
function single() {
  return (
    // comment
    true
  );
}

function multi() {
  return (
    // comment 1
    true
  ) ||
  (
    // comment 2
    true
  );
}
```
Generates:
```javascript
function single() {
  return (
    // comment
    true
  );
}

function multi() {
  return
  // comment 1
  true ||
  // comment 2
  true;
}
```
